/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, GNU /opt/rh/gcc-toolset-14/root/usr/bin/c++ 14.2.1) */

module pe_ctrl(clk, rst_n, spi_sclk, spi_mosi, spi_cs_n, spi_miso, run, host_we, host_imem_sel, host_addr, host_wdata, load_active, load_error, words_written);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input spi_sclk;
  wire spi_sclk;
  input spi_mosi;
  wire spi_mosi;
  input spi_cs_n;
  wire spi_cs_n;
  output spi_miso;
  wire spi_miso;
  input run;
  wire run;
  output host_we;
  wire host_we;
  output host_imem_sel;
  wire host_imem_sel;
  output [9:0] host_addr;
  wire [9:0] host_addr;
  output [15:0] host_wdata;
  wire [15:0] host_wdata;
  output load_active;
  wire load_active;
  output load_error;
  wire load_error;
  output [15:0] words_written;
  wire [15:0] words_written;
  wire [9:0] _000_;
  wire [15:0] _001_;
  wire _002_;
  wire [14:0] _003_;
  wire _004_;
  wire [15:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire [9:0] addr;
  wire [3:0] bit_cnt;
  wire [3:0] echo_falls;
  wire [15:0] echo_shreg;
  wire [15:0] echo_word;
  wire mosi_s0;
  wire mosi_s1;
  wire sclk_s0;
  wire sclk_s1;
  wire sclk_s1d;
  wire [14:0] shreg;
  wire we_r;
  wire [15:0] word_data;
  wire word_ready;
  wire [2:0] wstate;
  sg13g2_inv_1 _300_ (
    .A(spi_cs_n),
    .Y(_014_)
  );
  sg13g2_inv_1 _301_ (
    .A(bit_cnt[3]),
    .Y(_058_)
  );
  sg13g2_inv_1 _302_ (
    .A(words_written[1]),
    .Y(_059_)
  );
  sg13g2_inv_1 _303_ (
    .A(echo_falls[3]),
    .Y(_060_)
  );
  sg13g2_inv_1 _304_ (
    .A(words_written[12]),
    .Y(_061_)
  );
  sg13g2_inv_1 _305_ (
    .A(words_written[11]),
    .Y(_062_)
  );
  sg13g2_inv_1 _306_ (
    .A(shreg[12]),
    .Y(_063_)
  );
  sg13g2_inv_1 _307_ (
    .A(shreg[11]),
    .Y(_064_)
  );
  sg13g2_inv_1 _308_ (
    .A(shreg[10]),
    .Y(_065_)
  );
  sg13g2_inv_1 _309_ (
    .A(shreg[9]),
    .Y(_066_)
  );
  sg13g2_inv_1 _310_ (
    .A(shreg[8]),
    .Y(_067_)
  );
  sg13g2_inv_1 _311_ (
    .A(shreg[7]),
    .Y(_068_)
  );
  sg13g2_inv_1 _312_ (
    .A(shreg[6]),
    .Y(_069_)
  );
  sg13g2_inv_1 _313_ (
    .A(shreg[5]),
    .Y(_070_)
  );
  sg13g2_inv_1 _314_ (
    .A(shreg[4]),
    .Y(_071_)
  );
  sg13g2_inv_1 _315_ (
    .A(shreg[3]),
    .Y(_072_)
  );
  sg13g2_inv_1 _316_ (
    .A(shreg[2]),
    .Y(_073_)
  );
  sg13g2_inv_1 _317_ (
    .A(shreg[1]),
    .Y(_074_)
  );
  sg13g2_inv_1 _318_ (
    .A(shreg[0]),
    .Y(_075_)
  );
  sg13g2_inv_1 _319_ (
    .A(mosi_s1),
    .Y(_076_)
  );
  sg13g2_inv_1 _320_ (
    .A(shreg[13]),
    .Y(_077_)
  );
  sg13g2_inv_1 _321_ (
    .A(addr[9]),
    .Y(_078_)
  );
  sg13g2_inv_1 _322_ (
    .A(word_ready),
    .Y(_079_)
  );
  sg13g2_inv_1 _323_ (
    .A(word_data[15]),
    .Y(_080_)
  );
  sg13g2_inv_1 _324_ (
    .A(we_r),
    .Y(_081_)
  );
  sg13g2_inv_1 _325_ (
    .A(sclk_s1),
    .Y(_082_)
  );
  sg13g2_a21oi_1 _326_ (
    .A1(wstate[2]),
    .A2(run),
    .B1(wstate[1]),
    .Y(_083_)
  );
  sg13g2_o21ai_1 _327_ (
    .A1(_006_),
    .A2(word_ready),
    .B1(_083_),
    .Y(_084_)
  );
  sg13g2_a21oi_1 _328_ (
    .A1(run),
    .A2(word_ready),
    .B1(_084_),
    .Y(_012_)
  );
  sg13g2_nor2b_1 _329_ (
    .A(run),
    .B_N(wstate[1]),
    .Y(_085_)
  );
  sg13g2_nand2b_1 _330_ (
    .A_N(run),
    .B(wstate[1]),
    .Y(_086_)
  );
  sg13g2_nor2b_1 _331_ (
    .A(_009_),
    .B_N(_007_),
    .Y(_087_)
  );
  sg13g2_nand2b_1 _332_ (
    .A_N(_009_),
    .B(_007_),
    .Y(_088_)
  );
  sg13g2_nor2_1 _333_ (
    .A(_085_),
    .B(_088_),
    .Y(_089_)
  );
  sg13g2_nand2_1 _334_ (
    .A(_086_),
    .B(_087_),
    .Y(_090_)
  );
  sg13g2_and2_1 _335_ (
    .A(words_written[3]),
    .B(words_written[2]),
    .X(_091_)
  );
  sg13g2_nand3_1 _336_ (
    .A(words_written[3]),
    .B(words_written[2]),
    .C(words_written[4]),
    .Y(_092_)
  );
  sg13g2_nand3_1 _337_ (
    .A(words_written[7]),
    .B(words_written[6]),
    .C(words_written[5]),
    .Y(_093_)
  );
  sg13g2_nand4_1 _338_ (
    .A(words_written[1]),
    .B(words_written[12]),
    .C(words_written[10]),
    .D(words_written[8]),
    .Y(_094_)
  );
  sg13g2_nand3_1 _339_ (
    .A(words_written[0]),
    .B(words_written[11]),
    .C(words_written[9]),
    .Y(_095_)
  );
  sg13g2_nor4_1 _340_ (
    .A(_092_),
    .B(_093_),
    .C(_094_),
    .D(_095_),
    .Y(_096_)
  );
  sg13g2_and2_1 _341_ (
    .A(_085_),
    .B(_096_),
    .X(_097_)
  );
  sg13g2_nand3_1 _342_ (
    .A(words_written[13]),
    .B(_085_),
    .C(_096_),
    .Y(_098_)
  );
  sg13g2_nand2_1 _343_ (
    .A(words_written[14]),
    .B(_090_),
    .Y(_099_)
  );
  sg13g2_mux2_1 _344_ (
    .A0(words_written[14]),
    .A1(_099_),
    .S(_098_),
    .X(_100_)
  );
  sg13g2_inv_1 _345_ (
    .A(_100_),
    .Y(_005_[14])
  );
  sg13g2_a21oi_1 _346_ (
    .A1(words_written[13]),
    .A2(_090_),
    .B1(_097_),
    .Y(_101_)
  );
  sg13g2_a21oi_1 _347_ (
    .A1(words_written[13]),
    .A2(_097_),
    .B1(_101_),
    .Y(_005_[13])
  );
  sg13g2_nand3b_1 _348_ (
    .A_N(run),
    .B(wstate[1]),
    .C(words_written[0]),
    .Y(_102_)
  );
  sg13g2_nor2_1 _349_ (
    .A(_059_),
    .B(_102_),
    .Y(_103_)
  );
  sg13g2_nor4_1 _350_ (
    .A(_059_),
    .B(_092_),
    .C(_093_),
    .D(_102_),
    .Y(_104_)
  );
  sg13g2_and2_1 _351_ (
    .A(words_written[8]),
    .B(_104_),
    .X(_105_)
  );
  sg13g2_nand4_1 _352_ (
    .A(words_written[10]),
    .B(words_written[9]),
    .C(words_written[8]),
    .D(_104_),
    .Y(_106_)
  );
  sg13g2_o21ai_1 _353_ (
    .A1(_062_),
    .A2(_106_),
    .B1(_090_),
    .Y(_107_)
  );
  sg13g2_nand3b_1 _354_ (
    .A_N(_106_),
    .B(_061_),
    .C(words_written[11]),
    .Y(_108_)
  );
  sg13g2_o21ai_1 _355_ (
    .A1(_061_),
    .A2(_107_),
    .B1(_108_),
    .Y(_005_[12])
  );
  sg13g2_a21oi_1 _356_ (
    .A1(_062_),
    .A2(_106_),
    .B1(_107_),
    .Y(_005_[11])
  );
  sg13g2_a21oi_1 _357_ (
    .A1(words_written[9]),
    .A2(_105_),
    .B1(words_written[10]),
    .Y(_109_)
  );
  sg13g2_nand2_1 _358_ (
    .A(_090_),
    .B(_106_),
    .Y(_110_)
  );
  sg13g2_nor2_1 _359_ (
    .A(_109_),
    .B(_110_),
    .Y(_005_[10])
  );
  sg13g2_o21ai_1 _360_ (
    .A1(words_written[9]),
    .A2(_105_),
    .B1(_090_),
    .Y(_111_)
  );
  sg13g2_a21oi_1 _361_ (
    .A1(words_written[9]),
    .A2(_105_),
    .B1(_111_),
    .Y(_005_[9])
  );
  sg13g2_o21ai_1 _362_ (
    .A1(words_written[8]),
    .A2(_104_),
    .B1(_090_),
    .Y(_112_)
  );
  sg13g2_nor2_1 _363_ (
    .A(_105_),
    .B(_112_),
    .Y(_005_[8])
  );
  sg13g2_nor3_1 _364_ (
    .A(_059_),
    .B(_092_),
    .C(_102_),
    .Y(_113_)
  );
  sg13g2_and2_1 _365_ (
    .A(words_written[5]),
    .B(_113_),
    .X(_114_)
  );
  sg13g2_nand2_1 _366_ (
    .A(words_written[6]),
    .B(_114_),
    .Y(_115_)
  );
  sg13g2_nand2_1 _367_ (
    .A(words_written[7]),
    .B(_090_),
    .Y(_116_)
  );
  sg13g2_a21oi_1 _368_ (
    .A1(_115_),
    .A2(_116_),
    .B1(_104_),
    .Y(_005_[7])
  );
  sg13g2_a21oi_1 _369_ (
    .A1(words_written[6]),
    .A2(_090_),
    .B1(_114_),
    .Y(_117_)
  );
  sg13g2_a21oi_1 _370_ (
    .A1(words_written[6]),
    .A2(_114_),
    .B1(_117_),
    .Y(_005_[6])
  );
  sg13g2_a21oi_1 _371_ (
    .A1(words_written[5]),
    .A2(_090_),
    .B1(_113_),
    .Y(_118_)
  );
  sg13g2_nor2_1 _372_ (
    .A(_114_),
    .B(_118_),
    .Y(_005_[5])
  );
  sg13g2_a22oi_1 _373_ (
    .A1(words_written[4]),
    .A2(_090_),
    .B1(_091_),
    .B2(_103_),
    .Y(_119_)
  );
  sg13g2_nor2_1 _374_ (
    .A(_113_),
    .B(_119_),
    .Y(_005_[4])
  );
  sg13g2_a22oi_1 _375_ (
    .A1(words_written[3]),
    .A2(_090_),
    .B1(_103_),
    .B2(words_written[2]),
    .Y(_120_)
  );
  sg13g2_a21oi_1 _376_ (
    .A1(_091_),
    .A2(_103_),
    .B1(_120_),
    .Y(_005_[3])
  );
  sg13g2_a21oi_1 _377_ (
    .A1(words_written[2]),
    .A2(_090_),
    .B1(_103_),
    .Y(_121_)
  );
  sg13g2_a21oi_1 _378_ (
    .A1(words_written[2]),
    .A2(_103_),
    .B1(_121_),
    .Y(_005_[2])
  );
  sg13g2_and2_1 _379_ (
    .A(_059_),
    .B(_102_),
    .X(_122_)
  );
  sg13g2_nor3_1 _380_ (
    .A(_089_),
    .B(_103_),
    .C(_122_),
    .Y(_005_[1])
  );
  sg13g2_a21oi_1 _381_ (
    .A1(words_written[0]),
    .A2(_088_),
    .B1(_085_),
    .Y(_123_)
  );
  sg13g2_a21oi_1 _382_ (
    .A1(words_written[0]),
    .A2(_085_),
    .B1(_123_),
    .Y(_005_[0])
  );
  sg13g2_nor2b_1 _383_ (
    .A(run),
    .B_N(_007_),
    .Y(load_active)
  );
  sg13g2_nor2_1 _384_ (
    .A(load_error),
    .B(sclk_s1d),
    .Y(_124_)
  );
  sg13g2_and4_1 _385_ (
    .A(_079_),
    .B(sclk_s1),
    .C(load_active),
    .D(_124_),
    .X(_125_)
  );
  sg13g2_and3_1 _386_ (
    .A(bit_cnt[2]),
    .B(bit_cnt[1]),
    .C(bit_cnt[0]),
    .X(_126_)
  );
  sg13g2_nand3_1 _387_ (
    .A(bit_cnt[2]),
    .B(bit_cnt[1]),
    .C(bit_cnt[0]),
    .Y(_127_)
  );
  sg13g2_o21ai_1 _388_ (
    .A1(_058_),
    .A2(_127_),
    .B1(_125_),
    .Y(_128_)
  );
  sg13g2_nand3_1 _389_ (
    .A(shreg[13]),
    .B(_088_),
    .C(_128_),
    .Y(_129_)
  );
  sg13g2_o21ai_1 _390_ (
    .A1(_063_),
    .A2(_128_),
    .B1(_129_),
    .Y(_003_[13])
  );
  sg13g2_nand3_1 _391_ (
    .A(shreg[12]),
    .B(_088_),
    .C(_128_),
    .Y(_130_)
  );
  sg13g2_o21ai_1 _392_ (
    .A1(_064_),
    .A2(_128_),
    .B1(_130_),
    .Y(_003_[12])
  );
  sg13g2_nand3_1 _393_ (
    .A(shreg[11]),
    .B(_088_),
    .C(_128_),
    .Y(_131_)
  );
  sg13g2_o21ai_1 _394_ (
    .A1(_065_),
    .A2(_128_),
    .B1(_131_),
    .Y(_003_[11])
  );
  sg13g2_nand3_1 _395_ (
    .A(shreg[10]),
    .B(_088_),
    .C(_128_),
    .Y(_132_)
  );
  sg13g2_o21ai_1 _396_ (
    .A1(_066_),
    .A2(_128_),
    .B1(_132_),
    .Y(_003_[10])
  );
  sg13g2_nand3_1 _397_ (
    .A(shreg[9]),
    .B(_088_),
    .C(_128_),
    .Y(_133_)
  );
  sg13g2_o21ai_1 _398_ (
    .A1(_067_),
    .A2(_128_),
    .B1(_133_),
    .Y(_003_[9])
  );
  sg13g2_nand3_1 _399_ (
    .A(shreg[8]),
    .B(_088_),
    .C(_128_),
    .Y(_134_)
  );
  sg13g2_o21ai_1 _400_ (
    .A1(_068_),
    .A2(_128_),
    .B1(_134_),
    .Y(_003_[8])
  );
  sg13g2_nand3_1 _401_ (
    .A(shreg[7]),
    .B(_088_),
    .C(_128_),
    .Y(_135_)
  );
  sg13g2_o21ai_1 _402_ (
    .A1(_069_),
    .A2(_128_),
    .B1(_135_),
    .Y(_003_[7])
  );
  sg13g2_nand3_1 _403_ (
    .A(shreg[6]),
    .B(_088_),
    .C(_128_),
    .Y(_136_)
  );
  sg13g2_o21ai_1 _404_ (
    .A1(_070_),
    .A2(_128_),
    .B1(_136_),
    .Y(_003_[6])
  );
  sg13g2_nand3_1 _405_ (
    .A(shreg[5]),
    .B(_088_),
    .C(_128_),
    .Y(_137_)
  );
  sg13g2_o21ai_1 _406_ (
    .A1(_071_),
    .A2(_128_),
    .B1(_137_),
    .Y(_003_[5])
  );
  sg13g2_nand3_1 _407_ (
    .A(shreg[4]),
    .B(_088_),
    .C(_128_),
    .Y(_138_)
  );
  sg13g2_o21ai_1 _408_ (
    .A1(_072_),
    .A2(_128_),
    .B1(_138_),
    .Y(_003_[4])
  );
  sg13g2_nand3_1 _409_ (
    .A(shreg[3]),
    .B(_088_),
    .C(_128_),
    .Y(_139_)
  );
  sg13g2_o21ai_1 _410_ (
    .A1(_073_),
    .A2(_128_),
    .B1(_139_),
    .Y(_003_[3])
  );
  sg13g2_nand3_1 _411_ (
    .A(shreg[2]),
    .B(_088_),
    .C(_128_),
    .Y(_140_)
  );
  sg13g2_o21ai_1 _412_ (
    .A1(_074_),
    .A2(_128_),
    .B1(_140_),
    .Y(_003_[2])
  );
  sg13g2_nand3_1 _413_ (
    .A(shreg[1]),
    .B(_088_),
    .C(_128_),
    .Y(_141_)
  );
  sg13g2_o21ai_1 _414_ (
    .A1(_075_),
    .A2(_128_),
    .B1(_141_),
    .Y(_003_[1])
  );
  sg13g2_nand3_1 _415_ (
    .A(shreg[0]),
    .B(_088_),
    .C(_128_),
    .Y(_142_)
  );
  sg13g2_o21ai_1 _416_ (
    .A1(_076_),
    .A2(_128_),
    .B1(_142_),
    .Y(_003_[0])
  );
  sg13g2_nand2_1 _417_ (
    .A(echo_word[14]),
    .B(_086_),
    .Y(_143_)
  );
  sg13g2_nand2_1 _418_ (
    .A(word_data[14]),
    .B(_085_),
    .Y(_144_)
  );
  sg13g2_a21oi_1 _419_ (
    .A1(_143_),
    .A2(_144_),
    .B1(_089_),
    .Y(_001_[14])
  );
  sg13g2_nand2_1 _420_ (
    .A(echo_word[13]),
    .B(_086_),
    .Y(_145_)
  );
  sg13g2_nand2_1 _421_ (
    .A(word_data[13]),
    .B(_085_),
    .Y(_146_)
  );
  sg13g2_a21oi_1 _422_ (
    .A1(_145_),
    .A2(_146_),
    .B1(_089_),
    .Y(_001_[13])
  );
  sg13g2_nand2_1 _423_ (
    .A(echo_word[12]),
    .B(_086_),
    .Y(_147_)
  );
  sg13g2_nand2_1 _424_ (
    .A(word_data[12]),
    .B(_085_),
    .Y(_148_)
  );
  sg13g2_a21oi_1 _425_ (
    .A1(_147_),
    .A2(_148_),
    .B1(_089_),
    .Y(_001_[12])
  );
  sg13g2_nand2_1 _426_ (
    .A(echo_word[11]),
    .B(_086_),
    .Y(_149_)
  );
  sg13g2_nand2_1 _427_ (
    .A(word_data[11]),
    .B(_085_),
    .Y(_150_)
  );
  sg13g2_a21oi_1 _428_ (
    .A1(_149_),
    .A2(_150_),
    .B1(_089_),
    .Y(_001_[11])
  );
  sg13g2_nand2_1 _429_ (
    .A(echo_word[10]),
    .B(_086_),
    .Y(_151_)
  );
  sg13g2_nand2_1 _430_ (
    .A(word_data[10]),
    .B(_085_),
    .Y(_152_)
  );
  sg13g2_a21oi_1 _431_ (
    .A1(_151_),
    .A2(_152_),
    .B1(_089_),
    .Y(_001_[10])
  );
  sg13g2_nand2_1 _432_ (
    .A(echo_word[9]),
    .B(_086_),
    .Y(_153_)
  );
  sg13g2_nand2_1 _433_ (
    .A(word_data[9]),
    .B(_085_),
    .Y(_154_)
  );
  sg13g2_a21oi_1 _434_ (
    .A1(_153_),
    .A2(_154_),
    .B1(_089_),
    .Y(_001_[9])
  );
  sg13g2_nand2_1 _435_ (
    .A(echo_word[8]),
    .B(_086_),
    .Y(_155_)
  );
  sg13g2_nand2_1 _436_ (
    .A(word_data[8]),
    .B(_085_),
    .Y(_156_)
  );
  sg13g2_a21oi_1 _437_ (
    .A1(_155_),
    .A2(_156_),
    .B1(_089_),
    .Y(_001_[8])
  );
  sg13g2_nand2_1 _438_ (
    .A(echo_word[7]),
    .B(_086_),
    .Y(_157_)
  );
  sg13g2_nand2_1 _439_ (
    .A(word_data[7]),
    .B(_085_),
    .Y(_158_)
  );
  sg13g2_a21oi_1 _440_ (
    .A1(_157_),
    .A2(_158_),
    .B1(_089_),
    .Y(_001_[7])
  );
  sg13g2_nand2_1 _441_ (
    .A(echo_word[6]),
    .B(_086_),
    .Y(_159_)
  );
  sg13g2_nand2_1 _442_ (
    .A(word_data[6]),
    .B(_085_),
    .Y(_160_)
  );
  sg13g2_a21oi_1 _443_ (
    .A1(_159_),
    .A2(_160_),
    .B1(_089_),
    .Y(_001_[6])
  );
  sg13g2_nand2_1 _444_ (
    .A(echo_word[5]),
    .B(_086_),
    .Y(_161_)
  );
  sg13g2_nand2_1 _445_ (
    .A(word_data[5]),
    .B(_085_),
    .Y(_162_)
  );
  sg13g2_a21oi_1 _446_ (
    .A1(_161_),
    .A2(_162_),
    .B1(_089_),
    .Y(_001_[5])
  );
  sg13g2_nand2_1 _447_ (
    .A(echo_word[4]),
    .B(_086_),
    .Y(_163_)
  );
  sg13g2_nand2_1 _448_ (
    .A(word_data[4]),
    .B(_085_),
    .Y(_164_)
  );
  sg13g2_a21oi_1 _449_ (
    .A1(_163_),
    .A2(_164_),
    .B1(_089_),
    .Y(_001_[4])
  );
  sg13g2_nand2_1 _450_ (
    .A(echo_word[3]),
    .B(_086_),
    .Y(_165_)
  );
  sg13g2_nand2_1 _451_ (
    .A(word_data[3]),
    .B(_085_),
    .Y(_166_)
  );
  sg13g2_a21oi_1 _452_ (
    .A1(_165_),
    .A2(_166_),
    .B1(_089_),
    .Y(_001_[3])
  );
  sg13g2_nand2_1 _453_ (
    .A(echo_word[2]),
    .B(_086_),
    .Y(_167_)
  );
  sg13g2_nand2_1 _454_ (
    .A(word_data[2]),
    .B(_085_),
    .Y(_168_)
  );
  sg13g2_a21oi_1 _455_ (
    .A1(_167_),
    .A2(_168_),
    .B1(_089_),
    .Y(_001_[2])
  );
  sg13g2_nand2_1 _456_ (
    .A(echo_word[1]),
    .B(_086_),
    .Y(_169_)
  );
  sg13g2_nand2_1 _457_ (
    .A(word_data[1]),
    .B(_085_),
    .Y(_170_)
  );
  sg13g2_a21oi_1 _458_ (
    .A1(_169_),
    .A2(_170_),
    .B1(_089_),
    .Y(_001_[1])
  );
  sg13g2_nand2_1 _459_ (
    .A(echo_word[0]),
    .B(_086_),
    .Y(_171_)
  );
  sg13g2_nand2_1 _460_ (
    .A(word_data[0]),
    .B(_085_),
    .Y(_172_)
  );
  sg13g2_a21oi_1 _461_ (
    .A1(_171_),
    .A2(_172_),
    .B1(_089_),
    .Y(_001_[0])
  );
  sg13g2_nand3_1 _462_ (
    .A(addr[8]),
    .B(_086_),
    .C(_088_),
    .Y(_173_)
  );
  sg13g2_nand2_1 _463_ (
    .A(addr[1]),
    .B(addr[0]),
    .Y(_174_)
  );
  sg13g2_nand3_1 _464_ (
    .A(addr[1]),
    .B(addr[0]),
    .C(addr[2]),
    .Y(_175_)
  );
  sg13g2_and4_1 _465_ (
    .A(addr[1]),
    .B(addr[0]),
    .C(addr[3]),
    .D(addr[2]),
    .X(_176_)
  );
  sg13g2_nand2_1 _466_ (
    .A(addr[4]),
    .B(_176_),
    .Y(_177_)
  );
  sg13g2_nand3_1 _467_ (
    .A(addr[4]),
    .B(addr[5]),
    .C(_176_),
    .Y(_178_)
  );
  sg13g2_and4_1 _468_ (
    .A(addr[4]),
    .B(addr[6]),
    .C(addr[5]),
    .D(_176_),
    .X(_179_)
  );
  sg13g2_nand4_1 _469_ (
    .A(addr[4]),
    .B(addr[6]),
    .C(addr[5]),
    .D(_176_),
    .Y(_180_)
  );
  sg13g2_nand3_1 _470_ (
    .A(addr[7]),
    .B(addr[8]),
    .C(_179_),
    .Y(_181_)
  );
  sg13g2_a21oi_1 _471_ (
    .A1(addr[9]),
    .A2(_088_),
    .B1(_181_),
    .Y(_182_)
  );
  sg13g2_a21oi_1 _472_ (
    .A1(addr[7]),
    .A2(_179_),
    .B1(addr[8]),
    .Y(_183_)
  );
  sg13g2_nand2b_1 _473_ (
    .A_N(_183_),
    .B(_085_),
    .Y(_184_)
  );
  sg13g2_o21ai_1 _474_ (
    .A1(_182_),
    .A2(_184_),
    .B1(_173_),
    .Y(_000_[8])
  );
  sg13g2_xnor2_1 _475_ (
    .A(addr[7]),
    .B(_180_),
    .Y(_185_)
  );
  sg13g2_nor2_1 _476_ (
    .A(_086_),
    .B(_185_),
    .Y(_186_)
  );
  sg13g2_nand4_1 _477_ (
    .A(addr[7]),
    .B(addr[8]),
    .C(addr[9]),
    .D(_179_),
    .Y(_187_)
  );
  sg13g2_nand2b_1 _478_ (
    .A_N(_187_),
    .B(_088_),
    .Y(_188_)
  );
  sg13g2_nand2_1 _479_ (
    .A(addr[7]),
    .B(_088_),
    .Y(_189_)
  );
  sg13g2_a22oi_1 _480_ (
    .A1(_186_),
    .A2(_188_),
    .B1(_189_),
    .B2(_086_),
    .Y(_000_[7])
  );
  sg13g2_nand2b_1 _481_ (
    .A_N(addr[6]),
    .B(_178_),
    .Y(_190_)
  );
  sg13g2_a21oi_1 _482_ (
    .A1(_180_),
    .A2(_190_),
    .B1(_086_),
    .Y(_191_)
  );
  sg13g2_nand2_1 _483_ (
    .A(addr[6]),
    .B(_088_),
    .Y(_192_)
  );
  sg13g2_a22oi_1 _484_ (
    .A1(_188_),
    .A2(_191_),
    .B1(_192_),
    .B2(_086_),
    .Y(_000_[6])
  );
  sg13g2_nand2b_1 _485_ (
    .A_N(addr[5]),
    .B(_177_),
    .Y(_193_)
  );
  sg13g2_a21oi_1 _486_ (
    .A1(_178_),
    .A2(_193_),
    .B1(_086_),
    .Y(_194_)
  );
  sg13g2_nand2_1 _487_ (
    .A(addr[5]),
    .B(_088_),
    .Y(_195_)
  );
  sg13g2_a22oi_1 _488_ (
    .A1(_188_),
    .A2(_194_),
    .B1(_195_),
    .B2(_086_),
    .Y(_000_[5])
  );
  sg13g2_or2_1 _489_ (
    .A(addr[4]),
    .B(_176_),
    .X(_196_)
  );
  sg13g2_a21oi_1 _490_ (
    .A1(_177_),
    .A2(_196_),
    .B1(_086_),
    .Y(_197_)
  );
  sg13g2_nand2_1 _491_ (
    .A(addr[4]),
    .B(_088_),
    .Y(_198_)
  );
  sg13g2_a22oi_1 _492_ (
    .A1(_188_),
    .A2(_197_),
    .B1(_198_),
    .B2(_086_),
    .Y(_000_[4])
  );
  sg13g2_xnor2_1 _493_ (
    .A(addr[3]),
    .B(_175_),
    .Y(_199_)
  );
  sg13g2_nor2_1 _494_ (
    .A(_086_),
    .B(_199_),
    .Y(_200_)
  );
  sg13g2_nand2_1 _495_ (
    .A(addr[3]),
    .B(_088_),
    .Y(_201_)
  );
  sg13g2_a22oi_1 _496_ (
    .A1(_188_),
    .A2(_200_),
    .B1(_201_),
    .B2(_086_),
    .Y(_000_[3])
  );
  sg13g2_nand2b_1 _497_ (
    .A_N(addr[2]),
    .B(_174_),
    .Y(_202_)
  );
  sg13g2_a21oi_1 _498_ (
    .A1(_175_),
    .A2(_202_),
    .B1(_086_),
    .Y(_203_)
  );
  sg13g2_nand2_1 _499_ (
    .A(addr[2]),
    .B(_088_),
    .Y(_204_)
  );
  sg13g2_a22oi_1 _500_ (
    .A1(_188_),
    .A2(_203_),
    .B1(_204_),
    .B2(_086_),
    .Y(_000_[2])
  );
  sg13g2_or2_1 _501_ (
    .A(addr[1]),
    .B(addr[0]),
    .X(_205_)
  );
  sg13g2_a21oi_1 _502_ (
    .A1(_174_),
    .A2(_205_),
    .B1(_086_),
    .Y(_206_)
  );
  sg13g2_nand2_1 _503_ (
    .A(addr[1]),
    .B(_088_),
    .Y(_207_)
  );
  sg13g2_a22oi_1 _504_ (
    .A1(_188_),
    .A2(_206_),
    .B1(_207_),
    .B2(_086_),
    .Y(_000_[1])
  );
  sg13g2_nand2_1 _505_ (
    .A(addr[0]),
    .B(_088_),
    .Y(_208_)
  );
  sg13g2_and2_1 _506_ (
    .A(addr[0]),
    .B(_085_),
    .X(_209_)
  );
  sg13g2_a22oi_1 _507_ (
    .A1(_086_),
    .A2(_208_),
    .B1(_209_),
    .B2(_188_),
    .Y(_000_[0])
  );
  sg13g2_nor2b_1 _508_ (
    .A(run),
    .B_N(wstate[2]),
    .Y(_010_)
  );
  sg13g2_and4_1 _509_ (
    .A(_007_),
    .B(_009_),
    .C(sclk_s1d),
    .D(_082_),
    .X(_210_)
  );
  sg13g2_nor2_1 _510_ (
    .A(_087_),
    .B(_210_),
    .Y(_211_)
  );
  sg13g2_nand2_1 _511_ (
    .A(echo_shreg[14]),
    .B(_211_),
    .Y(_212_)
  );
  sg13g2_nand3_1 _512_ (
    .A(echo_falls[1]),
    .B(echo_falls[0]),
    .C(echo_falls[2]),
    .Y(_213_)
  );
  sg13g2_nor2_1 _513_ (
    .A(_060_),
    .B(_213_),
    .Y(_214_)
  );
  sg13g2_or2_1 _514_ (
    .A(_060_),
    .B(_213_),
    .X(_215_)
  );
  sg13g2_nor2_1 _515_ (
    .A(echo_word[13]),
    .B(_215_),
    .Y(_216_)
  );
  sg13g2_o21ai_1 _516_ (
    .A1(echo_shreg[13]),
    .A2(_214_),
    .B1(_210_),
    .Y(_217_)
  );
  sg13g2_o21ai_1 _517_ (
    .A1(_216_),
    .A2(_217_),
    .B1(_212_),
    .Y(_016_)
  );
  sg13g2_nand2_1 _518_ (
    .A(echo_shreg[13]),
    .B(_211_),
    .Y(_218_)
  );
  sg13g2_nor2_1 _519_ (
    .A(echo_word[12]),
    .B(_215_),
    .Y(_219_)
  );
  sg13g2_o21ai_1 _520_ (
    .A1(echo_shreg[12]),
    .A2(_214_),
    .B1(_210_),
    .Y(_220_)
  );
  sg13g2_o21ai_1 _521_ (
    .A1(_219_),
    .A2(_220_),
    .B1(_218_),
    .Y(_017_)
  );
  sg13g2_nand2_1 _522_ (
    .A(echo_shreg[12]),
    .B(_211_),
    .Y(_221_)
  );
  sg13g2_nor2_1 _523_ (
    .A(echo_word[11]),
    .B(_215_),
    .Y(_222_)
  );
  sg13g2_o21ai_1 _524_ (
    .A1(echo_shreg[11]),
    .A2(_214_),
    .B1(_210_),
    .Y(_223_)
  );
  sg13g2_o21ai_1 _525_ (
    .A1(_222_),
    .A2(_223_),
    .B1(_221_),
    .Y(_018_)
  );
  sg13g2_nand2_1 _526_ (
    .A(echo_shreg[11]),
    .B(_211_),
    .Y(_224_)
  );
  sg13g2_nor2_1 _527_ (
    .A(echo_word[10]),
    .B(_215_),
    .Y(_225_)
  );
  sg13g2_o21ai_1 _528_ (
    .A1(echo_shreg[10]),
    .A2(_214_),
    .B1(_210_),
    .Y(_226_)
  );
  sg13g2_o21ai_1 _529_ (
    .A1(_225_),
    .A2(_226_),
    .B1(_224_),
    .Y(_019_)
  );
  sg13g2_nand2_1 _530_ (
    .A(echo_shreg[10]),
    .B(_211_),
    .Y(_227_)
  );
  sg13g2_nor2_1 _531_ (
    .A(echo_word[9]),
    .B(_215_),
    .Y(_228_)
  );
  sg13g2_o21ai_1 _532_ (
    .A1(echo_shreg[9]),
    .A2(_214_),
    .B1(_210_),
    .Y(_229_)
  );
  sg13g2_o21ai_1 _533_ (
    .A1(_228_),
    .A2(_229_),
    .B1(_227_),
    .Y(_020_)
  );
  sg13g2_nand2_1 _534_ (
    .A(echo_shreg[9]),
    .B(_211_),
    .Y(_230_)
  );
  sg13g2_nor2_1 _535_ (
    .A(echo_word[8]),
    .B(_215_),
    .Y(_231_)
  );
  sg13g2_o21ai_1 _536_ (
    .A1(echo_shreg[8]),
    .A2(_214_),
    .B1(_210_),
    .Y(_232_)
  );
  sg13g2_o21ai_1 _537_ (
    .A1(_231_),
    .A2(_232_),
    .B1(_230_),
    .Y(_021_)
  );
  sg13g2_nand2_1 _538_ (
    .A(echo_shreg[8]),
    .B(_211_),
    .Y(_233_)
  );
  sg13g2_nor2_1 _539_ (
    .A(echo_word[7]),
    .B(_215_),
    .Y(_234_)
  );
  sg13g2_o21ai_1 _540_ (
    .A1(echo_shreg[7]),
    .A2(_214_),
    .B1(_210_),
    .Y(_235_)
  );
  sg13g2_o21ai_1 _541_ (
    .A1(_234_),
    .A2(_235_),
    .B1(_233_),
    .Y(_022_)
  );
  sg13g2_nand2_1 _542_ (
    .A(echo_shreg[7]),
    .B(_211_),
    .Y(_236_)
  );
  sg13g2_nor2_1 _543_ (
    .A(echo_word[6]),
    .B(_215_),
    .Y(_237_)
  );
  sg13g2_o21ai_1 _544_ (
    .A1(echo_shreg[6]),
    .A2(_214_),
    .B1(_210_),
    .Y(_238_)
  );
  sg13g2_o21ai_1 _545_ (
    .A1(_237_),
    .A2(_238_),
    .B1(_236_),
    .Y(_023_)
  );
  sg13g2_nand2_1 _546_ (
    .A(echo_shreg[6]),
    .B(_211_),
    .Y(_239_)
  );
  sg13g2_nor2_1 _547_ (
    .A(echo_word[5]),
    .B(_215_),
    .Y(_240_)
  );
  sg13g2_o21ai_1 _548_ (
    .A1(echo_shreg[5]),
    .A2(_214_),
    .B1(_210_),
    .Y(_241_)
  );
  sg13g2_o21ai_1 _549_ (
    .A1(_240_),
    .A2(_241_),
    .B1(_239_),
    .Y(_024_)
  );
  sg13g2_nand2_1 _550_ (
    .A(echo_shreg[5]),
    .B(_211_),
    .Y(_242_)
  );
  sg13g2_nor2_1 _551_ (
    .A(echo_word[4]),
    .B(_215_),
    .Y(_243_)
  );
  sg13g2_o21ai_1 _552_ (
    .A1(echo_shreg[4]),
    .A2(_214_),
    .B1(_210_),
    .Y(_244_)
  );
  sg13g2_o21ai_1 _553_ (
    .A1(_243_),
    .A2(_244_),
    .B1(_242_),
    .Y(_025_)
  );
  sg13g2_nand2_1 _554_ (
    .A(echo_shreg[4]),
    .B(_211_),
    .Y(_245_)
  );
  sg13g2_nor2_1 _555_ (
    .A(echo_word[3]),
    .B(_215_),
    .Y(_246_)
  );
  sg13g2_o21ai_1 _556_ (
    .A1(echo_shreg[3]),
    .A2(_214_),
    .B1(_210_),
    .Y(_247_)
  );
  sg13g2_o21ai_1 _557_ (
    .A1(_246_),
    .A2(_247_),
    .B1(_245_),
    .Y(_026_)
  );
  sg13g2_nand2_1 _558_ (
    .A(echo_shreg[3]),
    .B(_211_),
    .Y(_248_)
  );
  sg13g2_nor2_1 _559_ (
    .A(echo_word[2]),
    .B(_215_),
    .Y(_249_)
  );
  sg13g2_o21ai_1 _560_ (
    .A1(echo_shreg[2]),
    .A2(_214_),
    .B1(_210_),
    .Y(_250_)
  );
  sg13g2_o21ai_1 _561_ (
    .A1(_249_),
    .A2(_250_),
    .B1(_248_),
    .Y(_027_)
  );
  sg13g2_nand2_1 _562_ (
    .A(echo_shreg[2]),
    .B(_211_),
    .Y(_251_)
  );
  sg13g2_nor2_1 _563_ (
    .A(echo_word[1]),
    .B(_215_),
    .Y(_252_)
  );
  sg13g2_o21ai_1 _564_ (
    .A1(echo_shreg[1]),
    .A2(_214_),
    .B1(_210_),
    .Y(_253_)
  );
  sg13g2_o21ai_1 _565_ (
    .A1(_252_),
    .A2(_253_),
    .B1(_251_),
    .Y(_028_)
  );
  sg13g2_nand2_1 _566_ (
    .A(echo_shreg[1]),
    .B(_211_),
    .Y(_254_)
  );
  sg13g2_nor2_1 _567_ (
    .A(echo_word[0]),
    .B(_215_),
    .Y(_255_)
  );
  sg13g2_o21ai_1 _568_ (
    .A1(echo_shreg[0]),
    .A2(_214_),
    .B1(_210_),
    .Y(_256_)
  );
  sg13g2_o21ai_1 _569_ (
    .A1(_255_),
    .A2(_256_),
    .B1(_254_),
    .Y(_029_)
  );
  sg13g2_and2_1 _570_ (
    .A(echo_shreg[0]),
    .B(_211_),
    .X(_030_)
  );
  sg13g2_a21oi_1 _571_ (
    .A1(echo_falls[1]),
    .A2(echo_falls[0]),
    .B1(echo_falls[2]),
    .Y(_257_)
  );
  sg13g2_a22oi_1 _572_ (
    .A1(echo_falls[2]),
    .A2(_211_),
    .B1(_213_),
    .B2(_210_),
    .Y(_258_)
  );
  sg13g2_nor2_1 _573_ (
    .A(_257_),
    .B(_258_),
    .Y(_031_)
  );
  sg13g2_xor2_1 _574_ (
    .A(echo_falls[1]),
    .B(echo_falls[0]),
    .X(_259_)
  );
  sg13g2_a22oi_1 _575_ (
    .A1(echo_falls[1]),
    .A2(_211_),
    .B1(_259_),
    .B2(_210_),
    .Y(_260_)
  );
  sg13g2_inv_1 _576_ (
    .A(_260_),
    .Y(_032_)
  );
  sg13g2_mux2_1 _577_ (
    .A0(_210_),
    .A1(_211_),
    .S(echo_falls[0]),
    .X(_033_)
  );
  sg13g2_a21oi_1 _578_ (
    .A1(bit_cnt[1]),
    .A2(bit_cnt[0]),
    .B1(bit_cnt[2]),
    .Y(_261_)
  );
  sg13g2_nor2b_1 _579_ (
    .A(_007_),
    .B_N(_009_),
    .Y(_262_)
  );
  sg13g2_nand2b_1 _580_ (
    .A_N(_007_),
    .B(_009_),
    .Y(_263_)
  );
  sg13g2_nor3_1 _581_ (
    .A(_087_),
    .B(_125_),
    .C(_262_),
    .Y(_264_)
  );
  sg13g2_a22oi_1 _582_ (
    .A1(_125_),
    .A2(_127_),
    .B1(_264_),
    .B2(bit_cnt[2]),
    .Y(_265_)
  );
  sg13g2_nor2_1 _583_ (
    .A(_261_),
    .B(_265_),
    .Y(_034_)
  );
  sg13g2_xor2_1 _584_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .X(_266_)
  );
  sg13g2_a22oi_1 _585_ (
    .A1(bit_cnt[1]),
    .A2(_264_),
    .B1(_266_),
    .B2(_125_),
    .Y(_267_)
  );
  sg13g2_inv_1 _586_ (
    .A(_267_),
    .Y(_035_)
  );
  sg13g2_mux2_1 _587_ (
    .A0(_125_),
    .A1(_264_),
    .S(bit_cnt[0]),
    .X(_036_)
  );
  sg13g2_and3_1 _588_ (
    .A(bit_cnt[3]),
    .B(_125_),
    .C(_126_),
    .X(_268_)
  );
  sg13g2_inv_1 _589_ (
    .A(_268_),
    .Y(_269_)
  );
  sg13g2_nor2_1 _590_ (
    .A(word_data[14]),
    .B(_268_),
    .Y(_270_)
  );
  sg13g2_a21oi_1 _591_ (
    .A1(_077_),
    .A2(_268_),
    .B1(_270_),
    .Y(_037_)
  );
  sg13g2_mux2_1 _592_ (
    .A0(word_data[13]),
    .A1(shreg[12]),
    .S(_268_),
    .X(_038_)
  );
  sg13g2_mux2_1 _593_ (
    .A0(word_data[12]),
    .A1(shreg[11]),
    .S(_268_),
    .X(_039_)
  );
  sg13g2_mux2_1 _594_ (
    .A0(word_data[11]),
    .A1(shreg[10]),
    .S(_268_),
    .X(_040_)
  );
  sg13g2_mux2_1 _595_ (
    .A0(word_data[10]),
    .A1(shreg[9]),
    .S(_268_),
    .X(_041_)
  );
  sg13g2_mux2_1 _596_ (
    .A0(word_data[9]),
    .A1(shreg[8]),
    .S(_268_),
    .X(_042_)
  );
  sg13g2_mux2_1 _597_ (
    .A0(word_data[8]),
    .A1(shreg[7]),
    .S(_268_),
    .X(_043_)
  );
  sg13g2_mux2_1 _598_ (
    .A0(word_data[7]),
    .A1(shreg[6]),
    .S(_268_),
    .X(_044_)
  );
  sg13g2_mux2_1 _599_ (
    .A0(word_data[6]),
    .A1(shreg[5]),
    .S(_268_),
    .X(_045_)
  );
  sg13g2_mux2_1 _600_ (
    .A0(word_data[5]),
    .A1(shreg[4]),
    .S(_268_),
    .X(_046_)
  );
  sg13g2_mux2_1 _601_ (
    .A0(word_data[4]),
    .A1(shreg[3]),
    .S(_268_),
    .X(_047_)
  );
  sg13g2_mux2_1 _602_ (
    .A0(word_data[3]),
    .A1(shreg[2]),
    .S(_268_),
    .X(_048_)
  );
  sg13g2_mux2_1 _603_ (
    .A0(word_data[2]),
    .A1(shreg[1]),
    .S(_268_),
    .X(_049_)
  );
  sg13g2_mux2_1 _604_ (
    .A0(word_data[1]),
    .A1(shreg[0]),
    .S(_268_),
    .X(_050_)
  );
  sg13g2_mux2_1 _605_ (
    .A0(word_data[0]),
    .A1(mosi_s1),
    .S(_268_),
    .X(_051_)
  );
  sg13g2_nor2b_1 _606_ (
    .A(run),
    .B_N(_187_),
    .Y(_271_)
  );
  sg13g2_nor4_1 _607_ (
    .A(bit_cnt[3]),
    .B(bit_cnt[2]),
    .C(bit_cnt[1]),
    .D(bit_cnt[0]),
    .Y(_272_)
  );
  sg13g2_nand3b_1 _608_ (
    .A_N(_006_),
    .B(word_ready),
    .C(run),
    .Y(_273_)
  );
  sg13g2_o21ai_1 _609_ (
    .A1(_263_),
    .A2(_272_),
    .B1(_273_),
    .Y(_274_)
  );
  sg13g2_a21oi_1 _610_ (
    .A1(load_error),
    .A2(_088_),
    .B1(_274_),
    .Y(_275_)
  );
  sg13g2_o21ai_1 _611_ (
    .A1(_083_),
    .A2(_271_),
    .B1(_275_),
    .Y(_002_)
  );
  sg13g2_nand2_1 _612_ (
    .A(run),
    .B(_087_),
    .Y(_276_)
  );
  sg13g2_nor2b_1 _613_ (
    .A(run),
    .B_N(words_written[14]),
    .Y(_277_)
  );
  sg13g2_and2_1 _614_ (
    .A(words_written[13]),
    .B(_277_),
    .X(_278_)
  );
  sg13g2_a22oi_1 _615_ (
    .A1(words_written[15]),
    .A2(_276_),
    .B1(_278_),
    .B2(_096_),
    .Y(_279_)
  );
  sg13g2_nand2b_1 _616_ (
    .A_N(_279_),
    .B(wstate[1]),
    .Y(_280_)
  );
  sg13g2_and3_1 _617_ (
    .A(words_written[15]),
    .B(_096_),
    .C(_278_),
    .X(_281_)
  );
  sg13g2_nand3b_1 _618_ (
    .A_N(wstate[1]),
    .B(words_written[15]),
    .C(_088_),
    .Y(_282_)
  );
  sg13g2_o21ai_1 _619_ (
    .A1(_280_),
    .A2(_281_),
    .B1(_282_),
    .Y(_005_[15])
  );
  sg13g2_nand3_1 _620_ (
    .A(shreg[14]),
    .B(_088_),
    .C(_128_),
    .Y(_283_)
  );
  sg13g2_o21ai_1 _621_ (
    .A1(_077_),
    .A2(_128_),
    .B1(_283_),
    .Y(_003_[14])
  );
  sg13g2_nand3_1 _622_ (
    .A(word_ready),
    .B(_088_),
    .C(_263_),
    .Y(_284_)
  );
  sg13g2_nand2b_1 _623_ (
    .A_N(wstate[2]),
    .B(_006_),
    .Y(_285_)
  );
  sg13g2_mux2_1 _624_ (
    .A0(wstate[1]),
    .A1(run),
    .S(_285_),
    .X(_286_)
  );
  sg13g2_a21oi_1 _625_ (
    .A1(_269_),
    .A2(_284_),
    .B1(_286_),
    .Y(_004_)
  );
  sg13g2_a21oi_1 _626_ (
    .A1(echo_word[15]),
    .A2(_088_),
    .B1(_085_),
    .Y(_287_)
  );
  sg13g2_a21oi_1 _627_ (
    .A1(_080_),
    .A2(_085_),
    .B1(_287_),
    .Y(_001_[15])
  );
  sg13g2_nand2_1 _628_ (
    .A(shreg[14]),
    .B(_268_),
    .Y(_288_)
  );
  sg13g2_o21ai_1 _629_ (
    .A1(_080_),
    .A2(_268_),
    .B1(_288_),
    .Y(_052_)
  );
  sg13g2_a22oi_1 _630_ (
    .A1(addr[9]),
    .A2(_088_),
    .B1(_187_),
    .B2(_085_),
    .Y(_289_)
  );
  sg13g2_a21oi_1 _631_ (
    .A1(_078_),
    .A2(_181_),
    .B1(_289_),
    .Y(_000_[9])
  );
  sg13g2_nor2_1 _632_ (
    .A(bit_cnt[3]),
    .B(_126_),
    .Y(_290_)
  );
  sg13g2_nand2_1 _633_ (
    .A(bit_cnt[3]),
    .B(_264_),
    .Y(_291_)
  );
  sg13g2_o21ai_1 _634_ (
    .A1(_128_),
    .A2(_290_),
    .B1(_291_),
    .Y(_053_)
  );
  sg13g2_a22oi_1 _635_ (
    .A1(echo_falls[3]),
    .A2(_211_),
    .B1(_215_),
    .B2(_210_),
    .Y(_292_)
  );
  sg13g2_a21oi_1 _636_ (
    .A1(_060_),
    .A2(_213_),
    .B1(_292_),
    .Y(_054_)
  );
  sg13g2_nand2_1 _637_ (
    .A(spi_miso),
    .B(_211_),
    .Y(_293_)
  );
  sg13g2_nor2_1 _638_ (
    .A(echo_word[15]),
    .B(_215_),
    .Y(_294_)
  );
  sg13g2_o21ai_1 _639_ (
    .A1(echo_shreg[15]),
    .A2(_214_),
    .B1(_210_),
    .Y(_295_)
  );
  sg13g2_o21ai_1 _640_ (
    .A1(_294_),
    .A2(_295_),
    .B1(_293_),
    .Y(_055_)
  );
  sg13g2_nor3_1 _641_ (
    .A(run),
    .B(_006_),
    .C(_079_),
    .Y(_011_)
  );
  sg13g2_nor4_1 _642_ (
    .A(wstate[1]),
    .B(_081_),
    .C(_087_),
    .D(_285_),
    .Y(_296_)
  );
  sg13g2_or2_1 _643_ (
    .A(_010_),
    .B(_296_),
    .X(_056_)
  );
  sg13g2_nor2_1 _644_ (
    .A(run),
    .B(_081_),
    .Y(host_we)
  );
  sg13g2_nand2_1 _645_ (
    .A(echo_shreg[15]),
    .B(_211_),
    .Y(_297_)
  );
  sg13g2_nor2_1 _646_ (
    .A(echo_word[14]),
    .B(_215_),
    .Y(_298_)
  );
  sg13g2_o21ai_1 _647_ (
    .A1(echo_shreg[14]),
    .A2(_214_),
    .B1(_210_),
    .Y(_299_)
  );
  sg13g2_o21ai_1 _648_ (
    .A1(_298_),
    .A2(_299_),
    .B1(_297_),
    .Y(_057_)
  );
  sg13g2_buf_1 _649_ (
    .A(_007_),
    .X(_015_)
  );
  sg13g2_buf_1 _650_ (
    .A(_008_),
    .X(_013_)
  );
  sg13g2_dfrbpq_1 _651_ (
    .CLK(clk),
    .D(_012_),
    .Q(_006_),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _652_ (
    .CLK(clk),
    .D(_010_),
    .Q(wstate[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _653_ (
    .CLK(clk),
    .D(_011_),
    .Q(wstate[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _654_ (
    .CLK(clk),
    .D(_055_),
    .Q(spi_miso),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _655_ (
    .CLK(clk),
    .D(_051_),
    .Q(word_data[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _656_ (
    .CLK(clk),
    .D(_050_),
    .Q(word_data[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _657_ (
    .CLK(clk),
    .D(_049_),
    .Q(word_data[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _658_ (
    .CLK(clk),
    .D(_048_),
    .Q(word_data[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _659_ (
    .CLK(clk),
    .D(_047_),
    .Q(word_data[4]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _660_ (
    .CLK(clk),
    .D(_046_),
    .Q(word_data[5]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _661_ (
    .CLK(clk),
    .D(_045_),
    .Q(word_data[6]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _662_ (
    .CLK(clk),
    .D(_044_),
    .Q(word_data[7]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _663_ (
    .CLK(clk),
    .D(_043_),
    .Q(word_data[8]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _664_ (
    .CLK(clk),
    .D(_042_),
    .Q(word_data[9]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _665_ (
    .CLK(clk),
    .D(_041_),
    .Q(word_data[10]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _666_ (
    .CLK(clk),
    .D(_040_),
    .Q(word_data[11]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _667_ (
    .CLK(clk),
    .D(_039_),
    .Q(word_data[12]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _668_ (
    .CLK(clk),
    .D(_038_),
    .Q(word_data[13]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _669_ (
    .CLK(clk),
    .D(_037_),
    .Q(word_data[14]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _670_ (
    .CLK(clk),
    .D(_052_),
    .Q(word_data[15]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _671_ (
    .CLK(clk),
    .D(_036_),
    .Q(bit_cnt[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _672_ (
    .CLK(clk),
    .D(_035_),
    .Q(bit_cnt[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _673_ (
    .CLK(clk),
    .D(_034_),
    .Q(bit_cnt[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _674_ (
    .CLK(clk),
    .D(_053_),
    .Q(bit_cnt[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _675_ (
    .CLK(clk),
    .D(_033_),
    .Q(echo_falls[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _676_ (
    .CLK(clk),
    .D(_032_),
    .Q(echo_falls[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _677_ (
    .CLK(clk),
    .D(_031_),
    .Q(echo_falls[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _678_ (
    .CLK(clk),
    .D(_054_),
    .Q(echo_falls[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _679_ (
    .CLK(clk),
    .D(_056_),
    .Q(we_r),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _680_ (
    .CLK(clk),
    .D(_030_),
    .Q(echo_shreg[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _681_ (
    .CLK(clk),
    .D(_029_),
    .Q(echo_shreg[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _682_ (
    .CLK(clk),
    .D(_028_),
    .Q(echo_shreg[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _683_ (
    .CLK(clk),
    .D(_027_),
    .Q(echo_shreg[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _684_ (
    .CLK(clk),
    .D(_026_),
    .Q(echo_shreg[4]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _685_ (
    .CLK(clk),
    .D(_025_),
    .Q(echo_shreg[5]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _686_ (
    .CLK(clk),
    .D(_024_),
    .Q(echo_shreg[6]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _687_ (
    .CLK(clk),
    .D(_023_),
    .Q(echo_shreg[7]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _688_ (
    .CLK(clk),
    .D(_022_),
    .Q(echo_shreg[8]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _689_ (
    .CLK(clk),
    .D(_021_),
    .Q(echo_shreg[9]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _690_ (
    .CLK(clk),
    .D(_020_),
    .Q(echo_shreg[10]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _691_ (
    .CLK(clk),
    .D(_019_),
    .Q(echo_shreg[11]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _692_ (
    .CLK(clk),
    .D(_018_),
    .Q(echo_shreg[12]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _693_ (
    .CLK(clk),
    .D(_017_),
    .Q(echo_shreg[13]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _694_ (
    .CLK(clk),
    .D(_016_),
    .Q(echo_shreg[14]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _695_ (
    .CLK(clk),
    .D(_057_),
    .Q(echo_shreg[15]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _696_ (
    .CLK(clk),
    .D(_002_),
    .Q(load_error),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _697_ (
    .CLK(clk),
    .D(_005_[0]),
    .Q(words_written[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _698_ (
    .CLK(clk),
    .D(_005_[1]),
    .Q(words_written[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _699_ (
    .CLK(clk),
    .D(_005_[2]),
    .Q(words_written[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _700_ (
    .CLK(clk),
    .D(_005_[3]),
    .Q(words_written[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _701_ (
    .CLK(clk),
    .D(_005_[4]),
    .Q(words_written[4]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _702_ (
    .CLK(clk),
    .D(_005_[5]),
    .Q(words_written[5]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _703_ (
    .CLK(clk),
    .D(_005_[6]),
    .Q(words_written[6]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _704_ (
    .CLK(clk),
    .D(_005_[7]),
    .Q(words_written[7]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _705_ (
    .CLK(clk),
    .D(_005_[8]),
    .Q(words_written[8]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _706_ (
    .CLK(clk),
    .D(_005_[9]),
    .Q(words_written[9]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _707_ (
    .CLK(clk),
    .D(_005_[10]),
    .Q(words_written[10]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _708_ (
    .CLK(clk),
    .D(_005_[11]),
    .Q(words_written[11]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _709_ (
    .CLK(clk),
    .D(_005_[12]),
    .Q(words_written[12]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _710_ (
    .CLK(clk),
    .D(_005_[13]),
    .Q(words_written[13]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _711_ (
    .CLK(clk),
    .D(_005_[14]),
    .Q(words_written[14]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _712_ (
    .CLK(clk),
    .D(_005_[15]),
    .Q(words_written[15]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _713_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(shreg[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _714_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(shreg[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _715_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(shreg[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _716_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(shreg[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _717_ (
    .CLK(clk),
    .D(_003_[4]),
    .Q(shreg[4]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _718_ (
    .CLK(clk),
    .D(_003_[5]),
    .Q(shreg[5]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _719_ (
    .CLK(clk),
    .D(_003_[6]),
    .Q(shreg[6]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _720_ (
    .CLK(clk),
    .D(_003_[7]),
    .Q(shreg[7]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _721_ (
    .CLK(clk),
    .D(_003_[8]),
    .Q(shreg[8]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _722_ (
    .CLK(clk),
    .D(_003_[9]),
    .Q(shreg[9]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _723_ (
    .CLK(clk),
    .D(_003_[10]),
    .Q(shreg[10]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _724_ (
    .CLK(clk),
    .D(_003_[11]),
    .Q(shreg[11]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _725_ (
    .CLK(clk),
    .D(_003_[12]),
    .Q(shreg[12]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _726_ (
    .CLK(clk),
    .D(_003_[13]),
    .Q(shreg[13]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _727_ (
    .CLK(clk),
    .D(_003_[14]),
    .Q(shreg[14]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _728_ (
    .CLK(clk),
    .D(_004_),
    .Q(word_ready),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _729_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(echo_word[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _730_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(echo_word[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _731_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(echo_word[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _732_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(echo_word[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _733_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(echo_word[4]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _734_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(echo_word[5]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _735_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(echo_word[6]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _736_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(echo_word[7]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _737_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(echo_word[8]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _738_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(echo_word[9]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _739_ (
    .CLK(clk),
    .D(_001_[10]),
    .Q(echo_word[10]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _740_ (
    .CLK(clk),
    .D(_001_[11]),
    .Q(echo_word[11]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _741_ (
    .CLK(clk),
    .D(_001_[12]),
    .Q(echo_word[12]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _742_ (
    .CLK(clk),
    .D(_001_[13]),
    .Q(echo_word[13]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _743_ (
    .CLK(clk),
    .D(_001_[14]),
    .Q(echo_word[14]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _744_ (
    .CLK(clk),
    .D(_001_[15]),
    .Q(echo_word[15]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _745_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(addr[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _746_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(addr[1]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _747_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(addr[2]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _748_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(addr[3]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _749_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(addr[4]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _750_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(addr[5]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _751_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(addr[6]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _752_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(addr[7]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _753_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(addr[8]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _754_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(addr[9]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _755_ (
    .CLK(clk),
    .D(spi_sclk),
    .Q(sclk_s0),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _756_ (
    .CLK(clk),
    .D(sclk_s0),
    .Q(sclk_s1),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _757_ (
    .CLK(clk),
    .D(sclk_s1),
    .Q(sclk_s1d),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _758_ (
    .CLK(clk),
    .D(spi_mosi),
    .Q(mosi_s0),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _759_ (
    .CLK(clk),
    .D(mosi_s0),
    .Q(mosi_s1),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _760_ (
    .CLK(clk),
    .D(_014_),
    .Q(_008_),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _761_ (
    .CLK(clk),
    .D(_013_),
    .Q(_007_),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbpq_1 _762_ (
    .CLK(clk),
    .D(_015_),
    .Q(_009_),
    .RESET_B(rst_n)
  );
  assign host_wdata = word_data;
  assign host_addr = addr;
  assign host_imem_sel = 1'h1;
endmodule
