// tb_pe_soc_uart.v — the software UART, end to end on real RTL.
//
// This is the test that matters for the project thesis: a UART implemented
// ENTIRELY in firmware (firmware/uart_echo.pe) running on pe_cpu inside
// pe_soc. No UART state machine exists in the RTL; the framing, bit
// timing and bit assembly are the program.
//
// The TB does what a host does: loads the program over the host interface,
// releases run, then drives the RX pin with a real 8N1 waveform and decodes the
// TX pin. Timing is generated from the same constants the SoC uses, so a
// mismatch in the baud divisor shows up as a wrong byte rather than a
// coincidence.
//
// Program: firmware/uart_echo.hex, generated by tools/fw/peasm.py.

`timescale 1ns / 1ps

module tb_pe_soc_uart;

  // 1024 with the SRAM swap (decisions/adr-004-program-counter-width.md).
  // The loader walks the WHOLE window: a short load leaves the tail as
  // x's, and an x instruction decodes as an x opcode.
  localparam int IMEM_WORDS = 1024;
  localparam int IAW = $clog2(IMEM_WORDS);
  localparam int DMEM_BYTES = 16;
  localparam int BAUD       = 115_200;

  // The TB keeps its OWN copy of the clock rate, because it has to generate a
  // clock and cannot ask the DUT for one -- CLK_HZ is a localparam inside
  // pe_soc now, not a parameter (see the header there for why). This copy
  // is a TEST FACT about the board, not a second configuration: if it ever
  // disagrees with the RTL, the TB simulates at one rate while the SoC believes
  // another, and the protocol timing assertions would be measuring nothing.
  // tb_pe_soc_uart is the check for that -- see reference/clock-arithmetic.md.
  localparam int CLK_HZ = 60_000_000;

  // 60 MHz clock: 16.667 ns period.
  localparam real CLK_NS = 1e9 / CLK_HZ;
  localparam real BIT_NS = 1e9 / BAUD;

  logic clk = 0, rst_n;

  // host interface
  logic        host_we, host_imem_sel, run;
  logic [IAW-1:0] host_addr;
  logic [15:0] host_wdata;

  // wire. The SoC's port is 8 bits wide with "outputs low, inputs high"
  // (rtl/pe_soc.v header): bit 0 = UART TX, bit 3 = UART RX. The TB keeps
  // its own single-bit view of each side and packs/unpacks at the port.
  logic rx_pin;                        // TB drives this
  wire  tx_pin;                        // SoC drives this: port bit 0
  wire  [7:0] pin_in_bus  = {4'b0, rx_pin, 3'b0};   // RX on bit 3
  wire  [7:0] pin_out_bus;
  wire  [7:0] pin_oe_bus;
  assign tx_pin = pin_out_bus[0];

  logic [9:0] dbg_pc;   // R2: full PC width (pe_soc exposes PCW bits)
  logic [7:0] dbg_a, dbg_timer;

  pe_soc #(
    .IMEM_WORDS(IMEM_WORDS), .DMEM_BYTES(DMEM_BYTES),
    .BAUD(BAUD)
  ) dut (
    .dbg_hold(1'b0), .dbg_step(1'b0),  // R3: debug control idle here
    .clk(clk), .rst_n(rst_n),
    .host_we(host_we), .host_imem_sel(host_imem_sel),
    .host_addr(host_addr), .host_wdata(host_wdata), .run(run),
    // R2: the host read port is idle in this TB (tied low, not floating:
    // an undriven input would make the address mux X and break the CPU read).
    .dbg_rd_req(1'b0), .dbg_rd_dmem(1'b0), .dbg_rd_addr(16'h0000),
    .dbg_rd_data(), .dbg_rd_valid(),
    .pin_in(pin_in_bus), .pin_out(pin_out_bus), .pin_oe(pin_oe_bus),
    .dbg_pc(dbg_pc), .dbg_a(dbg_a), .dbg_timer(dbg_timer)
  );

  always #(CLK_NS/2) clk = ~clk;

  integer errors = 0;
  task automatic check(input bit c, input string m);
    if (!c) begin $display("FAIL: %s @%0t", m, $time); errors++; end
  endtask

  // ---------------- firmware load ----------------
  logic [15:0] prog [0:IMEM_WORDS-1];
  integer i;

  task automatic load_firmware();
    // Path is relative to the sim/ run directory (regress/run_all.sh runs there)
    for (i = 0; i < IMEM_WORDS; i++) prog[i] = 16'hF000;   // NOP fill
    $readmemh("../firmware/uart_echo.hex", prog);
    for (i = 0; i < IMEM_WORDS; i++) begin
      @(posedge clk); #1;
      host_we = 1'b1; host_imem_sel = 1'b1;
      host_addr = i[IAW-1:0];
      host_wdata = prog[i];
    end
    @(posedge clk); #1;
    host_we = 1'b0;
  endtask

  // ---------------- wire driver / monitor ----------------
  // Drive one bit for one bit period.
  task automatic drive_bit(input bit b);
    rx_pin = b;
    #(BIT_NS);
  endtask

  task automatic send_byte(input [7:0] b);
    $display("  [%0t] send %02h: pc=%0d a=%02h run=%b tx=%b", $time, b, dbg_pc, dbg_a, run, tx_pin);
    drive_bit(1'b0);                     // start
    for (int k = 0; k < 8; k++) drive_bit(b[k]);   // LSB first
    drive_bit(1'b1);                     // stop
    $display("  [%0t] send %02h done: pc=%0d a=%02h", $time, b, dbg_pc, dbg_a);
  endtask

  // Decode the TX pin on a grid anchored to the start-bit edge. A free-running
  // grid drifts against the firmware's own tick loop.
  logic [7:0] rx_byte;
  logic       got_byte;

  // Edge monitor: the echo can begin while send_byte() is still clocking out its
  // own frame (RX and TX are separate pins), so the anchor edge must be LATCHED,
  // not waited for. A plain @(negedge tx_pin) lands one bit late and decodes the
  // byte shifted -- that is what this test caught on 2026-09-20.
  logic tx_edge_seen = 1'b0;
  time  tx_edge_time;
  always @(negedge tx_pin) if (run && !tx_edge_seen) begin
    tx_edge_seen <= 1'b1;
    tx_edge_time <= $time;
  end

  // Decode one UART byte from the TX pin.
  //
  // The sample grid is anchored to the START-BIT EDGE and the sample point is
  // the CENTRE of each bit. Two things matter here:
  //
  //  * A free-running grid (sampling every BIT_NS from some arbitrary start)
  //    drifts against the transmitter. The firmware's bit cell is ~1% off the
  //    nominal 8680 ns -- it is written in software, counting timer ticks, not
  //    dividing a clock -- and 1% of 10 bits is half a bit period by the stop
  //    bit, which corrupts the top data bits. Anchoring to the edge removes
  //    the accumulated offset; sampling at the centre leaves ~half a bit of
  //    slack on each side.
  //
  //  * The start bit itself is 1 bit period long, so the first sample is at
  //    1.5 bit periods after the edge (1 full bit to clear the start bit,
  //    plus half a bit to reach the centre of bit 0).
  task automatic expect_byte(input [7:0] want);
    got_byte = 1'b0;
    $display("  [%0t] waiting for TX start bit (want %02h)...", $time, want);
    wait (tx_edge_seen);
    $display("  [%0t] TX start bit seen (edge at %0t)", $time, tx_edge_time);
    for (int k = 0; k < 8; k++) begin
      while ($time < tx_edge_time + BIT_NS * (1.5 + k)) @(posedge clk);
      rx_byte[k] = tx_pin;               // centre of bit k, on the real clock
    end
    while ($time < tx_edge_time + BIT_NS * 9.0) @(posedge clk);
    check(tx_pin === 1'b1, "tx stop bit high");
    check(rx_byte === want,
          $sformatf("echoed byte: got %02h want %02h", rx_byte, want));
    got_byte = 1'b1;
    tx_edge_seen = 1'b0;                 // re-arm for the next byte
  endtask

  // ---------------- stimulus ----------------
  // Instrumentation. Ground truth for what the firmware drives, independent of
  // any decode: every write to the TX pin, and the RX byte that fed it.
  always @(posedge clk) if (run) begin
    if (dut.io_we && dut.io_port == 4'h1)
      $display("    TX_WRITE %b t=%0t", dut.io_wdata[0], $time);
    if (dut.dmem_we && dut.cpu_dmem_addr == 4'd15)
      $display("    RX_BYTE<=%02h t=%0t", dut.dmem_wdata, $time);
  end

  initial begin
    $dumpfile("tb_pe_soc_uart.vcd");
    $dumpvars(0, tb_pe_soc_uart);

    rst_n = 0; run = 0; host_we = 0; host_imem_sel = 0;
    host_addr = 0; host_wdata = 0;
    rx_pin = 1'b1;                       // idle high

    repeat (4) @(posedge clk); #1;
    rst_n = 1;
    @(posedge clk); #1;

    load_firmware();

    // Release the CPU. The pin must be idle-high and STABLE first: a glitch
    // during reset looks exactly like a start bit, and the firmware would
    // consume it, then spin waiting for a byte that already "arrived".
    rx_pin = 1'b1;
    repeat (4) @(posedge clk); #1;
    run = 1'b1;

    // Wait until the CPU is genuinely in its start-bit wait loop. A fixed
    // delay is a guess; watching the PC is a fact. pc 2 = IN A,PIN of
    // wait_idle, pc 3 = JZ wait_idle.
    wait (dbg_pc == 8'd2 || dbg_pc == 8'd3);
    $display("  [%0t] firmware is in the wait loop (pc=%0d) rx_pin=%b dut.pin_in=%b",
             $time, dbg_pc, rx_pin, dut.pin_in);
    #(BIT_NS);              // one bit of settle
    $display("  [%0t] after settle: pc=%0d rx_pin=%b dut.pin_in=%b",
             $time, dbg_pc, rx_pin, dut.pin_in);

    // ---- one byte through the loop ----
    send_byte(8'h41);
    expect_byte(8'h41);

    // ---- a second byte proves the receive loop re-arms ----
    #(BIT_NS * 24);                      // half-duplex turnaround
    send_byte(8'h42);
    expect_byte(8'h42);

    // ---- a byte pair that catches timing slips: 0x00 and 0xFF ----
    #(BIT_NS * 24);
    send_byte(8'h00);
    expect_byte(8'h00);

    #(BIT_NS * 24);
    send_byte(8'hFF);
    expect_byte(8'hFF);

    if (errors == 0) $display("PASS: tb_pe_soc_uart");
    else $display("FAILURES: %0d", errors);
    $finish;
  end

  // watchdog: the program is a polled loop, so a deadlock must be loud
  initial begin
    #(BIT_NS * 400);
    $display("FAIL: watchdog — firmware still running, no finish");
    $display("  pc=%0d a=%02h timer=%02h tx=%b", dbg_pc, dbg_a, dbg_timer, tx_pin);
    $finish;
  end

endmodule
