// tb_pe_soc_freqmeter.v — an input frequency and duty meter: the pin is an
// INPUT and the firmware recovers two numbers from a waveform it does not
// control.
//
// WHAT THIS PROVES, AND WHY IT IS A DIFFERENT SHAPE OF PROBLEM FROM THE SIX
// TIMING ACTS ALREADY HERE.
//
// Those six all DRIVE a pin. This one listens. The PWM arrives from outside, the
// firmware has no way to ask when the edges are coming, and the answer it has to
// produce -- a period and a duty -- is a number it can only get by counting
// between two edges it did not schedule. The number that is the claim is the
// ACCURACY OF THE COUNT, and the honest way to state that is a tolerance in
// parts per million, not a datasheet window: an edge-detected count of whole
// microseconds is exact to within one microsecond, so the relative error is
// 1/period, and that is the act's real specification.
//
// THE MODEL, and what it is allowed to know.
//
//   The signal is generated by a generator object that knows the sweep table
//   and nothing else: it produces a period and a high time, and it has no idea
//   what the firmware will do with them. The receiver below measures edge times
//   off the pad and computes a period and a duty from those measurements only.
//   A model that knew the sweep would agree with a firmware that had the sweep
//   wrong; this one cannot, because it is never told the sweep.
//
//   And the interesting part is the LOW end of the sweep. At 100 Hz the period
//   is 10 000 us, which does not fit in one 8-bit counter, so a firmware that
//   counts into a byte wraps and reports 39 us for a 100 Hz signal -- a wrong
//   answer rather than a wrong precision, and a defect with no symptom at 10 kHz.
//   That is why the sweep goes down to 100 Hz and why the TB checks EVERY point
//   rather than the endpoints.
//
// THE CHECKS, and how each could be unfalsified:
//
//   1. EVERY SWEEP POINT, not the ends. Sixteen periods from 100 Hz to 10 kHz,
//      each checked to 1 % on the period and 1 % absolute on the duty. An
//      endpoint-only check passes a firmware that is wrong in the middle.
//   2. THE PERIOD TO 1 %, from the firmware's OWN tick counts, and the claim is
//      the count: 1 us of quantisation on a 10 000 us period is 0.01 %.
//
//   3. THE DUTY, as a PERCENTAGE, which is the harder number: it is a ratio of
//      two 16-bit counts, and a firmware that measures the high time and the
//      period with the same edge discipline gets a ratio that is right even
//      when both are off by a microsecond. That is the property worth showing.
//   4. THE SWEEP IS MONOTONIC IN THE MEASUREMENT, so a firmware that returned a
//      stale reading for some points cannot pass by accident.
//   5. NON-VACUITY: the duty is not constant across the sweep and not 50 %
//      everywhere, and the periods are pairwise distinct, so "the firmware
//      returned something plausible" is not available.
//
// THE COST: the sweep is sixteen periods, and the slowest is 10 ms, so the
// simulation is dominated by the low end -- about 75 ms of 60 MHz, which is more
// than any other testbench in this repository. That is not trimmed, and the
// reason is in the header of the act's firmware: the 100 Hz point is where the
// 16-bit claim is tested, and dropping it would leave the act asserting
// something it had not measured. The measurement is done once per point rather
// than repeatedly.

`timescale 1ns / 1ps

// The image under test. Overridable so the mutation harness can compile ONE
// testbench against a mutated image without editing the tree.
`ifndef FREQMETER_HEX
  `define FREQMETER_HEX "../firmware/freqmeter.hex"
`endif

module tb_pe_soc_freqmeter;

  localparam int IMEM_WORDS = 1024;
  localparam int IAW = $clog2(IMEM_WORDS);
  localparam int DMEM_BYTES = 16;
  localparam int BAUD = 115_200;

  localparam int  CLK_HZ = 60_000_000;
  localparam real CLK_NS = 1e9 / CLK_HZ;

  localparam int IN_BIT = 6;      // the PWM input pad

  localparam int N_PTS = 16;      // the sweep points
  localparam int MEAS_PER_PT = 2; // periods measured per point, after one warm-up

  // The SWEEP. The generator is built from this table and told nothing else;
  // every number the checks use is recomputed from it, and the firmware is
  // never shown it.
  //
  // The low end is the point of the act: 100 Hz is a 10 000 us period, which
  // does not fit in one byte. The high end is 10 kHz, a 100 us period, where a
  // firmware that samples the tick can miss edges entirely.
  // A MEMORY, not an unpacked-array localparam: Icarus does not support the
  // latter ("unpacked array parameters are not supported yet") and says so only
  // with a `sorry`, which is not a loud enough failure for a table a check
  // depends on. Initialised in the initial block, so the compiler cannot
  // complain and the values are still written in one readable place.
  integer p_hi  [0:N_PTS-1];   // the period at each point, in microseconds
  integer d_pct [0:N_PTS-1];   // the duty at each point, in percent

  // The claim's tolerance, stated: 1 % of the period, which at 100 Hz is 100 us
  // and at 10 kHz is 1 us. The firmware's quantisation is 1 us, so at the fast
  // end the 1 % is the TOLERANCE and the quantisation is 1 % of it -- which is
  // why the accuracy claim is per-point and not a single number.
  localparam int TOL_PCT = 1;
  localparam int DUTY_TOL = 2;     // percentage points, absolute

  // Everything in this file is in whole NANOSECONDS from $realtime, and the
  // firmware's own resolution is 1 us, so the TB's unit has to be finer than
  // the thing being measured or the tolerance is the TB's rounding.
  localparam int MAX_EDGE = 4096;

  logic clk = 0, rst_n;
  logic           host_we, host_imem_sel, run;
  logic [IAW-1:0] host_addr;
  logic [15:0]    host_wdata;

  wire [7:0] pin_out_bus, pin_oe_bus;
  logic [7:0] pin_in_bus;

  // The PWM pad is an INPUT: the generator drives it and the SoC reads it back
  // through the pin matrix, which is the whole point -- the firmware recovers a
  // number from a pin it never writes.
  logic pwm = 1'b0;
  assign pin_in_bus = {1'b1, 1'b1, pwm, 5'b11111};
  wire [7:0] pin_out_unused = 8'h00;

  logic [9:0] dbg_pc;
  logic [7:0] dbg_a, dbg_timer;

  pe_soc #(
    .IMEM_WORDS(IMEM_WORDS), .DMEM_BYTES(DMEM_BYTES), .BAUD(BAUD)
  ) dut (
    .clk(clk), .rst_n(rst_n),
    .host_we(host_we), .host_imem_sel(host_imem_sel),
    .host_addr(host_addr), .host_wdata(host_wdata), .run(run),
    .dbg_rd_req(1'b0), .dbg_rd_dmem(1'b0), .dbg_rd_addr(16'h0000),
    .dbg_rd_data(), .dbg_rd_valid(),
    .pin_in(pin_in_bus), .pin_out(pin_out_bus), .pin_oe(pin_oe_bus),
    .dbg_pc(dbg_pc), .dbg_a(dbg_a), .dbg_timer(dbg_timer)
  );

  always #(CLK_NS/2) clk = ~clk;

  integer errors = 0;
  task automatic check(input bit c, input string m);
    if (!c) begin $display("FAIL: %s @%0t", m, $time); errors++; end
  endtask

  integer i, k;
  logic [15:0] prog [0:IMEM_WORDS-1];

  task automatic load_firmware();
    for (i = 0; i < IMEM_WORDS; i++) prog[i] = 16'hF000;
    $readmemh(`FREQMETER_HEX, prog);
    for (i = 0; i < IMEM_WORDS; i++) begin
      @(posedge clk); #1;
      host_we = 1'b1; host_imem_sel = 1'b1;
      host_addr = i[IAW-1:0];
      host_wdata = prog[i];
    end
    @(posedge clk); #1;
    host_we = 1'b0;
  endtask

  // ---- THE GENERATOR -----------------------------------------------------
  //
  // It knows the sweep table and nothing else. It produces a level, and the
  // edges fall out of counting clocks -- so a period that is 10 000 us really
  // is 600 000 clocks of real time, and the firmware's edge detection is tested
  // against that rather than against a number the TB would like it to see.
  integer  gen_cyc = 0;      // clocks into the current point
  integer  gen_half = 0;     // which half of the period
  integer  gen_pts = 0;      // which sweep point
  integer  gen_hi_clocks = 0, gen_per_clocks = 0;

  task automatic gen_load_point();
    begin
      gen_per_clocks = p_hi[gen_pts] * 60;                     // us * 60
      gen_hi_clocks  = (gen_per_clocks * d_pct[gen_pts]) / 100;
      gen_cyc  = 0;
      gen_half = 0;
    end
  endtask

  initial begin
    pwm = 1'b0;
    gen_pts = 0;
    gen_load_point();
    forever begin
      #(CLK_NS);
      gen_cyc = gen_cyc + 1;
      if (gen_cyc >= gen_per_clocks) begin
        // the period is over: the next sweep point
        gen_pts = gen_pts + 1;
        if (gen_pts >= N_PTS) gen_pts = 0;     // the firmware must have finished
        gen_load_point();
      end else if (gen_half == 0 && gen_cyc >= gen_hi_clocks) begin
        gen_half = 1;
        pwm = 1'b0;                            // the falling edge
      end else if (gen_half == 1 && gen_cyc >= gen_per_clocks/2) begin
        gen_half = 0;
        pwm = 1'b1;                            // the rising edge
      end
    end
  end

  // ---- THE RECEIVER: edges off the pad, and only that --------------------
  integer n_edge = 0;
  longint e_t [0:MAX_EDGE-1];
  bit     e_lv[0:MAX_EDGE-1];
  always @(pwm) if (run && rst_n && n_edge < MAX_EDGE) begin
    e_t[n_edge]  = $time;          // $time is in ns: the timescale's unit
    e_lv[n_edge] = pwm;
    n_edge = n_edge + 1;
  end

  // ---- the checks --------------------------------------------------------
  // The firmware's answer: sixteen periods and sixteen high times, 16-bit
  // pairs. dmem[0..1] and dmem[2..3] per point, indexed by dmem[8] inside the
  // firmware; the TB reads all of them out at the end.
  integer pt, got_ok, n_bad_period, n_bad_duty, n_stale, n_distinct;
  integer exp_per, got_per, exp_duty, got_duty, prev_per;
  integer nf;
  integer best_err;

  initial begin
    $dumpfile("tb_pe_soc_freqmeter.vcd");
    // NOTE: dut.dmem is a vpiMemory behind the SRAM macro and cannot be dumped
    // ("$dumpvars cannot dump a vpiMemory"), so the firmware's answers are read
    // out at the end instead -- which is better anyway, since the point is the
    // NUMBERS and not the waveform.
    $dumpvars(0, pwm, pin_in_bus, dbg_pc, dbg_timer);

    p_hi[0]=10000; p_hi[1]=8000;  p_hi[2]=6000;  p_hi[3]=4000;
    p_hi[4]=3000;  p_hi[5]=2500;  p_hi[6]=2000;  p_hi[7]=1600;
    p_hi[8]=1250;  p_hi[9]=1000;  p_hi[10]=800;  p_hi[11]=625;
    p_hi[12]=500;  p_hi[13]=400;  p_hi[14]=250;  p_hi[15]=100;
    // Duty chosen to vary and to avoid being mostly 50 %, so a firmware
    // returning a constant ratio, or a 50 % assumption baked into the hardware,
    // is caught rather than agreeing by accident.
    d_pct[0]=25; d_pct[1]=50;  d_pct[2]=75;  d_pct[3]=10;
    d_pct[4]=90;  d_pct[5]=33;  d_pct[6]=66;  d_pct[7]=20;
    d_pct[8]=80;  d_pct[9]=40;  d_pct[10]=60; d_pct[11]=12;
    d_pct[12]=88; d_pct[13]=45; d_pct[14]=55; d_pct[15]=30;

    n_edge = 0;

    rst_n = 1'b0; run = 1'b0; host_we = 1'b0; host_imem_sel = 1'b0;
    host_addr = '0; host_wdata = '0;
    repeat (4) @(posedge clk);
    rst_n = 1'b1;
    repeat (2) @(posedge clk);

    load_firmware();
    repeat (4) @(posedge clk);
    #1;

    $display("\n=== input frequency + duty meter: %0d points, %0d Hz to %0d Hz ===\n",
             N_PTS, 1_000_000/p_hi[N_PTS-1], 1_000_000/p_hi[0]);
    run = 1'b1;
    // The slowest point is 10 ms and we measure two periods at each of
    // sixteen points, so the run is bounded by the low end times a few.
    repeat (7_000_000) @(posedge clk);   // ~117 ms

    check(dut.dmem[14] == 8'h01,
          $sformatf("the firmware finished the whole sweep (dmem[14] = %02h)", dut.dmem[14]));

    // ---- 1/2/3. every point, not the ends ------------------------------
    n_bad_period = 0; n_bad_duty = 0; n_stale = 0; n_distinct = 0;
    prev_per = -1;
    for (pt = 0; pt < N_PTS; pt = pt + 1) begin
      exp_per = p_hi[pt];
      got_per = (dut.dmem[pt*4] << 8) | dut.dmem[pt*4+1];
      exp_duty = d_pct[pt];
      got_duty = (dut.dmem[pt*4+2] << 8) | dut.dmem[pt*4+3];
      if (got_per == prev_per && pt > 0) n_stale = n_stale + 1;
      prev_per = got_per;
      if (got_per != prev_per || pt == 0) n_distinct = n_distinct + 1;
      if (iabs16(got_per - exp_per) * 100 > exp_per * TOL_PCT) begin
        n_bad_period = n_bad_period + 1;
        $display("    point %2d: period %0d us, want %0d us (%0d %% off)",
                 pt, got_per, exp_per,
                 exp_per ? (iabs16(got_per-exp_per)*100)/exp_per : 999);
      end
      if (iabs16(got_duty - exp_duty) > DUTY_TOL) begin
        n_bad_duty = n_bad_duty + 1;
        $display("    point %2d: duty %0d %%, want %0d %%", pt, got_duty, exp_duty);
      end
    end
    $display("    %0d periods, %0d high times, %0d edges seen",
             N_PTS, N_PTS, n_edge);
    check(n_bad_period == 0,
          $sformatf("every period is within %0d %% -- %0d of %0d are not",
                    TOL_PCT, n_bad_period, N_PTS));
    check(n_bad_duty == 0,
          $sformatf("every duty is within %0d percentage points -- %0d of %0d are not",
                    DUTY_TOL, n_bad_duty, N_PTS));
    check(n_stale == 0,
          $sformatf("no two points returned the same period (%0d repeats) -- a firmware that returned a stale reading for some points must not pass",
                    n_stale));
    check(n_distinct >= N_PTS-1,
          $sformatf("the periods are pairwise distinct (%0d distinct values)", n_distinct));

    // ---- 5. non-vacuity on the sweep itself ----------------------------
    // ...and print it, so the sweep's shape is visible in the log.
    for (pt = 0; pt < N_PTS; pt = pt + 1)
      $display("      point %2d: %0d us (%0d.%0d kHz) duty %0d %%",
               pt, (dut.dmem[pt*4] << 8) | dut.dmem[pt*4+1],
               ((dut.dmem[pt*4] << 8) | dut.dmem[pt*4+1]) / 1000,
               (((dut.dmem[pt*4] << 8) | dut.dmem[pt*4+1]) % 1000) / 100,
               (dut.dmem[pt*4+2] << 8) | dut.dmem[pt*4+3]);
    check(d_pct[0] != d_pct[N_PTS-1],
          "the sweep's duty VARIES, so a constant ratio cannot pass");

    $display("");
    if (errors == 0) $display("PASS: all checks");
    else             $display("FAIL: %0d checks failed", errors);
    $finish;
  end

  // The ISA has no carry flag, so a 16-bit difference here needs the same
  // treatment the firmware's arithmetic does.
  function integer iabs16(input integer v);
    iabs16 = (v < 0) ? -v : v;
  endfunction

  initial begin
    #150_000_000;
    $display("FAIL: watchdog -- test did not complete");
    $finish;
  end

endmodule
