// tb_pe_ps2.v — PS/2 keyboard framing around pe_serdes.
//
// PS/2: 11-bit frame = start(0) + 8 data LSB-first + odd parity + stop(1).
// Device->host direction (clock generated by the device). The TB models
// the device: it shifts a frame out; the SERDES rx side captures the 8
// data bits through the strobe window, and the TB separately checks the
// parity line. A host inhibit (clock held low) pauses the frame —
// modeled as an idle gap between frames.

`timescale 1ns / 1ps

module tb_pe_ps2;

  localparam int MAXLEN = 32;
  localparam int LENW = $clog2(MAXLEN + 1);
  localparam int H = 8;  // clk cycles per PS/2 bit

  logic              clk, rst_n;
  logic              cfg_lsb_first, bit_en;
  logic              tx_load, tx_ser, tx_busy, tx_done;
  logic [MAXLEN-1:0] tx_data;
  logic [LENW-1:0]   tx_len;
  logic              rx_ser, rx_start, rx_busy, rx_valid;
  logic [MAXLEN-1:0] rx_data;
  logic [LENW-1:0]   rx_len;
  logic              ps2_clk, ps2_data;

  // Sticky event flags for the single-cycle pulses.
  logic rx_valid_seen;
  always @(posedge clk or negedge rst_n)
    if (!rst_n) rx_valid_seen <= 0;
    else if (rx_valid) rx_valid_seen <= 1'b1;

  pe_serdes #(.MAXLEN(MAXLEN)) dut (.*);

  initial clk = 0;
  always #5 clk = ~clk;

  integer errors = 0;

  task automatic check(input bit c, input string m);
    if (!c) begin $display("FAIL: %s @%0t", m, $time); errors++; end
  endtask

  function automatic bit odd_parity(input [7:0] d);
    return ~^d;  // odd parity: total ones (incl. parity bit) odd
  endfunction

  task automatic bit_cell();
    repeat (H) @(posedge clk); #1;
  endtask

  // Device sends one frame (make code). Host (SERDES) reads data bits.
  task automatic dev_send(input [7:0] b, input string tag);
    // start bit (data low while clock idles high)
    ps2_clk = 1'b1; ps2_data = 1'b0; bit_cell();
    ps2_clk = 1'b0; bit_cell();  // host samples on falling edge
    // arm rx: 8 data bits, LSB-first
    @(posedge clk); #1;
    cfg_lsb_first = 1'b1; rx_len = 8; rx_start = 1'b1;
    rx_valid_seen = 1'b0;
    @(posedge clk); #1; rx_start = 1'b0;
    for (int k = 0; k < 8; k++) begin
      ps2_data = b[k];           // LSB first
      rx_ser = ps2_data;
      ps2_clk = 1'b1; bit_cell();
      ps2_clk = 1'b0; bit_cell();
      bit_en = 1'b1; @(posedge clk); #1; bit_en = 1'b0;
    end
    // parity bit
    ps2_data = odd_parity(b);
    check(ps2_data === odd_parity(b), {tag, ": parity value"});
    ps2_clk = 1'b1; bit_cell();
    ps2_clk = 1'b0; bit_cell();
    // stop bit
    ps2_data = 1'b1;
    ps2_clk = 1'b1; bit_cell();
    ps2_clk = 1'b0; bit_cell();
    repeat (2) @(posedge clk); #1;
    check(rx_valid_seen === 1'b1, {tag, ": rx_valid"});
    check(rx_data[7:0] === b, {tag, ": payload"});
  endtask

  initial begin
    $dumpfile("tb_pe_ps2.vcd");
    $dumpvars(0, tb_pe_ps2);
    rst_n = 0; ps2_clk = 1; ps2_data = 1; bit_en = 0;
    cfg_lsb_first = 1; tx_load = 0; tx_data = 0; tx_len = 0;
    rx_ser = 0; rx_start = 0; rx_len = 0;
    repeat (3) @(posedge clk); #1; rst_n = 1;
    @(posedge clk); #1;

    dev_send(8'h1C, "ps2 make A");     // 'A' make code
    dev_send(8'hF0, "ps2 break prefix");
    dev_send(8'h1C, "ps2 break A");
    dev_send(8'hE0, "ps2 ext prefix");
    dev_send(8'h14, "ps2 ctrl-make");
    // host inhibit gap between frames (clock held low by host)
    ps2_clk = 1'b0; repeat (4 * H) @(posedge clk); #1;
    ps2_clk = 1'b1;
    dev_send(8'h45, "ps2 after inhibit");

    if (errors == 0) $display("PASS: tb_pe_ps2");
    else $display("FAILURES: %0d", errors);
    $finish;
  end

endmodule
